sudo: required
language: go
go:
- 1.11.x
- 1.12.x
env:
  matrix:
  - VERSION=7.0.0 ELASTIC_PASSWORD=secret ELASTIC_USERNAME=jdoe
  - VERSION=7.1.0 ELASTIC_PASSWORD=secret ELASTIC_USERNAME=jdoe
  - VERSION=7.2.0 ELASTIC_PASSWORD=secret ELASTIC_USERNAME=jdoe
addons:
  ssh_known_hosts: github.com
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" && ! $(which nc) ]] ; then sudo apt-get install -y netcat ; fi
- sudo sysctl -w vm.max_map_count=262144
- docker-compose up -d
- docker-compose exec elasticsearch chown -R 1000:1000 /usr/share/elasticsearch/backup
- docker-compose exec dev go get
- docker-compose exec dev go get github.com/stretchr/testify/assert
- docker-compose exec dev go get github.com/mattn/goveralls
install: true
script:
- docker-compose exec dev go test -failfast -v -covermode=count -coverprofile=coverage.out ./logger/... ./console/... ./ymlparser/... ./tests/...
