version: '3.3'

services:

  elasticsearch:
      build:
        context: elasticsearch/
        args:
          VERSION: $VERSION
      volumes:
        - elastic-backup:/usr/share/elasticsearch/backup
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      environment:
        - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
        - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      networks:
        - esnet
  
  dev:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URI=${ELASTICSEARCH_URI}"
      - "ELASTIC_USERNAME=${ELASTIC_USERNAME}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "GO111MODULE=on"
      - "SLACK_WEBHOOKS=${SLACK_WEBHOOKS}"
      - "PAGER_DUTY_ROUTING_KEY=${PAGER_DUTY_ROUTING_KEY}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "EMAIL_USERNAME=${EMAIL_USERNAME}"
      - "EMAIL_PASSWORD=${EMAIL_PASSWORD}" 
    volumes:
      - .:/go/src/scrubber
    networks:
      - esnet
  
  scrubber:
    build:
      context: ./
      dockerfile: Dockerfile.scrubber
    volumes:
      - ./tests/testdata/schedulerdata:/usr/share/testfiles:ro
    environment:
      - "ACTIONS_PATH=/usr/share/testfiles"
      - "ELASTICSEARCH_URI=${ELASTICSEARCH_URI}"
      - "ELASTIC_USERNAME=${ELASTIC_USERNAME}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    depends_on:
      - elasticsearch
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
    
volumes:
    elastic-backup: